//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfBooksClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="book", Namespace="http://schemas.datacontract.org/2004/07/booksdal")]
    [System.SerializableAttribute()]
    public partial class book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string authornameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bookcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string booknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string publishernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string authorname {
            get {
                return this.authornameField;
            }
            set {
                if ((object.ReferenceEquals(this.authornameField, value) != true)) {
                    this.authornameField = value;
                    this.RaisePropertyChanged("authorname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bookcode {
            get {
                return this.bookcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.bookcodeField, value) != true)) {
                    this.bookcodeField = value;
                    this.RaisePropertyChanged("bookcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bookname {
            get {
                return this.booknameField;
            }
            set {
                if ((object.ReferenceEquals(this.booknameField, value) != true)) {
                    this.booknameField = value;
                    this.RaisePropertyChanged("bookname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string publishername {
            get {
                return this.publishernameField;
            }
            set {
                if ((object.ReferenceEquals(this.publishernameField, value) != true)) {
                    this.publishernameField = value;
                    this.RaisePropertyChanged("publishername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBooks")]
    public interface IBooks {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBooks/findbycode", ReplyAction="http://tempuri.org/IBooks/findbycodeResponse")]
        WcfBooksClient.ServiceReference1.book findbycode(string bookcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBooks/findbycode", ReplyAction="http://tempuri.org/IBooks/findbycodeResponse")]
        System.Threading.Tasks.Task<WcfBooksClient.ServiceReference1.book> findbycodeAsync(string bookcode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBooksChannel : WcfBooksClient.ServiceReference1.IBooks, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BooksClient : System.ServiceModel.ClientBase<WcfBooksClient.ServiceReference1.IBooks>, WcfBooksClient.ServiceReference1.IBooks {
        
        public BooksClient() {
        }
        
        public BooksClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BooksClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BooksClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BooksClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfBooksClient.ServiceReference1.book findbycode(string bookcode) {
            return base.Channel.findbycode(bookcode);
        }
        
        public System.Threading.Tasks.Task<WcfBooksClient.ServiceReference1.book> findbycodeAsync(string bookcode) {
            return base.Channel.findbycodeAsync(bookcode);
        }
    }
}
